#!/bin/bash
echo "***** verification for database *****"
echo -e "\n"
echo "SELECT COUNT(*) FROM prices WHERE ticker='TSLA';"
sqlite3 portpulse.db "SELECT COUNT(*) FROM prices WHERE ticker='TSLA';"
echo ""
echo "SELECT * FROM prices WHERE ticker='TSLA' LIMIT 5;"
sqlite3 portpulse.db "SELECT * FROM prices WHERE ticker='TSLA' LIMIT 5;"
echo ""
echo "SELECT COUNT(*) FROM prices WHERE ticker='TSLL';"
sqlite3 portpulse.db "SELECT COUNT(*) FROM prices WHERE ticker='TSLL';"
echo ""
echo "SELECT * FROM prices WHERE ticker='TSLL' LIMIT 5;"
sqlite3 portpulse.db "SELECT * FROM prices WHERE ticker='TSLL' LIMIT 5;"
